name: 编译luci-app-vnt

on:
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 下载工具链
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          wget -qO /opt/sdk.tar.xz https://downloads.openwrt.org/releases/22.03.5/targets/rockchip/armv8/openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xJf /opt/sdk.tar.xz -C /opt
          git clone https://github.com/lmq8267/luci-app-vnt.git /opt/vnt
          sed -i 's/LUCI_DEPENDS:=+luci-lib-fs +kmod-tun/LUCI_DEPENDS:=/' /opt/vnt/luci-app-vnt/Makefile
          cd /opt/openwrt-sdk*/package
          cp -R /opt/vnt/luci-app-vnt .
          cd /opt/openwrt-sdk*
          ./scripts/feeds update -a
          make defconfig
      - name: 开始编译
        run: |
          cd /opt/openwrt-sdk*
          make package/luci-app-vnt/compile V=s -j1
          cd /opt/openwrt-sdk*/bin/packages/aarch64_generic/base
          ls
          mv *.ipk luci-app-vnt_all.ipk
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.c8 }}
            body: |
             > ### 编译时间 ：${{ env.build_time }}

             需要先去系统自带的软件包里已经安装 _**luci**_ 和 _**luci-base**_ 和 _**luci-compat**_ 和 _**[luci-lib-fs](https://github.com/lmq8267/luci-app-vnt/releases/download/1.0.0/luci-lib-fs_1.0-1_all.ipk)**_ 和 _**kmod-tun**_ 再安装这个ipk才能显示界面

             安装完成后找不到界面入口的，请注销登录关闭当前浏览器窗口重新打开或重启路由器
             
             ![image](https://github.com/lmq8267/luci-app-vnt/assets/119713693/5094717e-a301-4411-9450-c8b64d4a3ade)
             如果 状态-系统日志里 出现上述日志可以使用以下命令解决
             `sed -i 's/util/xml/' /usr/lib/lua/luci/model/cbi/vnt.lua`
           
            tag_name: 1.3.1.1
            files: /opt/openwrt-sdk*/bin/packages/aarch64_generic/base/*
     
